### ISSUE TITLE
Changing back from spectator mode does not respawn other player's tags

### ISSUE THREAD

**Issue by iso2013** [iso2013/MultiLineAPI#18]
This bug does not have any known fixes.

**Comment by jacobsandersen** [comment]
What about having a repeating task run to constantly refresh all tags every few seconds?

**Comment by DrkMatr1984** [comment]
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/player/PlayerGameModeChangeEvent.html

There's an event to detect gamemode changes in spigot that could be listened to, and if the player is changing from Spectator mode to another gamemode, refresh those tags. This way refreshing tags is done when needed instead of on a repeating task to save resources. Would that work?

**Comment by iso2013** [comment]
@simpleauthority @DrkMatr1984, I appreciate the suggestions but the problem is that refreshing the tag does not work - instead, every tag in the player's view distance would have to be disabled and re-enabled.

The refresh method re-sends the Entity Mount packets to re-mount the entities on the players' heads from the client's perspective.

In order to hide the tags from a spectator, the entities must be destroyed for the spectator so Entity Destroy packets are sent for the tags.
This causes the problem, because refreshing the other player's tags has no effect, since the client no longer knows of the tag entities. There's not a simple way to resend them with their attributes that I'm aware of.

**Comment by DrkMatr1984** [comment]
I see what you're saying. Well, this is a problem... I'll think about it a bunch and see if I can come up with a solution. There has to be some sort of way of refreshing the tags this way. You think you could store the entity in a temporary HashMap along with the Player it's attached to server side so that it can be re-sent to the correct client on refresh?

**Comment by DrkMatr1984** [comment]
Ahh, you would almost need a hasmap in a hashmap or create your own storage class because you'd also need to store the player who needs the tag resent to...
